AWSTemplateFormatVersion: 2010-09-09

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: "*.samhstn.com"
      ValidationMethod: DNS

Outputs:
  AcmCertArn:
    Value: !Ref Certificate
    Export:
      Name: SamhstnAcmCertArn
