AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Codebuild which runs on every push to github

Parameters:
  GithubOwner:
    Type: String
    Default: samhstn
  GithubRepo:
    Type: String
    Default: samhstn

Resources:
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: samhstn-codebuild-build-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: samhstn-codebuild-build-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource:
                  !Join [ ':', [ 'arn:aws:logs', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'log-group', '/aws/codebuild/*' ] ]

  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CodeBuild
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.14.1
        EnvironmentVariables:
          - Name: DESTINATION_BUCKET
            Type: PLAINTEXT
            # Currently unable to reference this dynamically, see:
            # https://stackoverflow.com/a/41727240/4699289
            Value: samhstn.com
      ServiceRole: !Ref BuildRole
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: !Join ["", ["https://github.com/", !Ref GithubOwner, "/", !Ref GithubRepo, ".git"]]
        BuildSpec: infra/testspec.yml
