AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Codebuild which runs on every push to github

Parameters:
  BuildRoleName:
    Type: String
    Default: samhstn-build-role

Resources:
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref BuildRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: samhstn-codebuild-build-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource:
                  !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject" # todo: specify just codepipeline bucket
                  - "s3:PutObject" # todo: specify samhstn.com bucket
                Resource: "*"

  Codebuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CodeBuild
      BadgeEnabled: true
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.14.1
        EnvironmentVariables:
          - Name: DESTINATION_BUCKET
            Type: PLAINTEXT
            # Currently unable to reference this dynamically, see:
            # https://stackoverflow.com/a/41727240/4699289
            Value: samhstn.com
      ServiceRole: !Ref BuildRoleName
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: https://github.com/{{resolve:ssm:/Samhstn/GithubOwner:1}}/{{resolve:ssm:/Samhstn/GithubRepo:1}}.git
        BuildSpec: infra/buildspecs/test.yaml
        ReportBuildStatus: true
      Triggers:
        Webhook: true
        FilterGroups:
          - - ExcludeMatchedPattern: false
              Pattern: PUSH
              Type: EVENT

  Test:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Test
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        # See all options here:
        # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        Image: aws/codebuild/nodejs:10.14.1
      ServiceRole: !Ref BuildRoleName
      Source:
        Type: CODEPIPELINE
        BuildSpec: infra/buildspecs/test.yaml

  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Build
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ubuntu-base:14.04
        EnvironmentVariables:
          - Name: DESTINATION_BUCKET
            Type: PLAINTEXT
            # Currently unable to reference this dynamically, see:
            # https://stackoverflow.com/a/41727240/4699289
            Value: samhstn.com
      ServiceRole: !Ref BuildRoleName
      Source:
        Type: CODEPIPELINE
        BuildSpec: infra/buildspecs/build.yaml
