AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DeploymentRoleArn:
    Type: String

Resources:
  Route53Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub Route53Role-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DeploymentRoleArn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: route-53-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # TODO: specify samhstn domain aliases
              - Resource: '*'
                Effect: Allow
                Action: 'route53:*'

Outputs:
  Route53RoleArn:
    Description: Role for creating aliases to point at cross account services.
    Value: !GetAtt Route53Role.Arn
