AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: >
  + Creates and stores secrets
  + Sets up a lambda webhook for dynamic builds
  + Creates ECR repo

Parameters:
  GithubPAToken:
    Type: String
    NoEcho: true

  GithubMasterBranch:
    Type: String
    Default: master

  Route53RoleArn:
    Type: String
    Default: ''
    Description: To be updated once role has been created in root account.

  SamhstnHostedZoneId:
    Type: String

Conditions:
  IsRoute53RoleSet: !Not [ !Equals [!Ref Route53RoleArn, '']]

Resources:
  GithubSecretParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubSecret
      GenerateSecretString:
        ExcludePunctuation: true

  GithubPATokenParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubPAToken
      SecretString: !Ref GithubPAToken

  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/Webhook
      RetentionInDays: 14

  BuildProjectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/codebuild/BuildProject
      RetentionInDays: 14

  DeleteProjectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/codebuild/DeleteProject
      RetentionInDays: 14

  WebhookFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - GithubSecretParameter
      - WebhookLogGroup
    Properties:
      FunctionName: Webhook
      Runtime: python3.8
      Role: !GetAtt WebhookRole.Arn
      Handler: index.handler
      Environment:
        Variables:
          GITHUB_MASTER_BRANCH: !Ref GithubMasterBranch
          BUILD_PROJECT: !Ref BuildDynamicProject
          DELETE_PROJECT: !Ref DeleteDynamicProject
      CodeUri: webhook
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /webhook

  WebhookRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExecuteWebhook
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: execute-webhook
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: codebuild:StartBuild
                Resource:
                  - !GetAtt BuildDynamicProject.Arn
                  - !GetAtt DeleteDynamicProject.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt WebhookLogGroup.Arn
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref GithubSecretParameter
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/ExecuteWebhook

  BuildDynamicProject:
    Type: AWS::CodeBuild::Project
    Condition: IsRoute53RoleSet
    Properties:
      Name: BuildProject
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:  !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/samhstn:latest
        EnvironmentVariables:
          - Name: S3_CODEBUILD_BUCKET_NAME
            Value: !ImportValue CodeBuildBucketName
          - Name: ROUTE_53_ROLE_ARN
            Value: !Ref Route53RoleArn
          - Name: SAMHSTN_HOSTED_ZONE_ID
            Value: !Ref SamhstnHostedZoneId
      ServiceRole: !Ref DeploymentRole
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: https://github.com/samhstn/samhstn.git
        BuildSpec: ./infra/samhstn/buildspec.yml
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE

  DeleteDynamicProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DeleteProject
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:  !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/samhstn:latest
        EnvironmentVariables:
          - Name: CODE_BUILD_BUCKET_NAME
            Value: !ImportValue CodeBuildBucketName
      ServiceRole: !Ref DeploymentRole
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: https://github.com/samhstn/samhstn.git
        BuildSpec: ./infra/samhstn/deletespec.yml

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
               - codepipeline.amazonaws.com
               - codedeploy.amazonaws.com
               - codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: DeploymentPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !GetAtt BuildProjectLogGroup.Arn
                  - !GetAtt DeleteProjectLogGroup.Arn
              - Effect: Allow
                Action:
                  - 'ssm:GetParameters'
                  - 'cloudformation:*'
                  - 'iam:*'
                  - 'ec2:*'
                  - 'codedeploy:*'
                  - 'autoscaling:*'
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:CreateTargetGroup
                  - elasticloadbalancing:DeleteTargetGroup
                Resource: '*'
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - !Sub
                    - arn:aws:s3:::${CodeBuildBucketName}
                    - { CodeBuildBucketName: !ImportValue CodeBuildBucketName}
                  - !Sub
                    - arn:aws:s3:::${CodeBuildBucketName}/*
                    - { CodeBuildBucketName: !ImportValue CodeBuildBucketName}
              - !If
                - IsRoute53RoleSet
                - Resource: !Ref Route53RoleArn
                  Effect: Allow
                  Action:
                    - sts:AssumeRole
                - !Ref AWS::NoValue

  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: samhstn
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

Outputs:
  WebhookEndpoint:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook
    Export:
      Name: WebhookEndpoint
  DeploymentRoleArn:
    Value: !GetAtt DeploymentRole.Arn
    Export:
      Name: DeploymentRoleArn
